import CustomerDiscovery from "./modules/restaurant/CustomerDiscovery";
import AdminCatalog from "./modules/restaurant/AdminCatalog";
import { FormEvent, useEffect, useState, type ReactNode } from "react";
import { ArrowLeftIcon, ArrowRightStartOnRectangleIcon, BellIcon, ChartBarIcon, ClockIcon, HeartIcon, HomeIcon, MagnifyingGlassIcon, MapPinIcon, PlusIcon, ShoppingBagIcon, StarIcon, TruckIcon, UserGroupIcon, XMarkIcon } from "@heroicons/react/24/outline";
import { authenticationService, type Customer, type Session } from "./modules/authentication";
import CustomerCart from "./modules/cart/CustomerCart";
import { useCustomerCart } from "./modules/cart/useCustomerCart";
import { dishId, dishService, type Dish } from "./modules/dishes";
import { orderService, type Order } from "./modules/order";
import { restaurantId, restaurantService, type Restaurant } from "./modules/restaurant";
const foodImages = ["/images/dishes/pizza.jpg", "/images/dishes/pasta.webp", "/images/dishes/salad.jpg", "/images/dishes/pizza.jpg", "/images/dishes/pasta.webp"];
const dishPicture = (index: number) => foodImages[index % foodImages.length];
const restaurantImages = [
  "/images/restaurants/restaurant-italian.jpg",
  "/images/restaurants/restaurant-modern.jpg",
  "/images/restaurants/restaurant-japanese.jpg",
];
const sampleRestaurants: Restaurant[] = [
  { id: 1, name: "Basil & Ember", cuisine: "Italian · Wood-fired", address: "Downtown Dubai", rating: 4.8, deliveryTime: "25–35 min", image: restaurantImages[0] },
  { id: 2, name: "Saffron Street", cuisine: "Indian · Modern", address: "Business Bay", rating: 4.7, deliveryTime: "30–40 min", image: restaurantImages[1] },
  { id: 3, name: "Sora Kitchen", cuisine: "Japanese · Sushi", address: "Dubai Marina", rating: 4.9, deliveryTime: "20–30 min", image: restaurantImages[2] },
];
const sampleDishes: Dish[] = [
  { id: 1, name: "Truffle Burrata Pizza", description: "Wild mushrooms, creamy burrata, truffle oil and basil", price: 58, category: "Popular", image: foodImages[3] },
  { id: 2, name: "Roasted Tomato Rigatoni", description: "Slow-roasted tomato, parmesan, chilli and fresh herbs", price: 46, category: "Pasta", image: foodImages[4] },
  { id: 3, name: "Garden Citrus Salad", description: "Baby leaves, citrus, avocado, pistachio and feta", price: 39, category: "Fresh", image: foodImages[1] },
];
const rid = restaurantId;
const did = dishId;
const money = (n: number) => `AED ${Number(n || 0).toFixed(0)}`;
type AdminSection = "overview" | "orders" | "restaurants" | "dishes" | "customers";

function AdminDashboard({ session, section, onSectionChange, onBrowse, onSignOut }: { session: Session; section: AdminSection; onSectionChange: (section: AdminSection) => void; onBrowse: () => void; onSignOut: () => void }) {
  const [customerQuery, setCustomerQuery] = useState("");
  const [orderQuery, setOrderQuery] = useState("");
  const [customers, setCustomers] = useState<Customer[]>([
    { customerId: 1, name: "Maya Khan", email: "maya@example.com", phone: "+971 50 234 1872", address: "Downtown Dubai", orders: 18, spent: 2140, status: "Active" },
    { customerId: 2, name: "Omar Ali", email: "omar@example.com", phone: "+971 55 641 2098", address: "Business Bay", orders: 12, spent: 1385, status: "Active" },
    { customerId: 3, name: "Sara Noor", email: "sara@example.com", phone: "+971 52 881 4502", address: "Dubai Marina", orders: 9, spent: 970, status: "Active" },
    { customerId: 4, name: "Leo Martin", email: "leo@example.com", phone: "+971 56 310 7741", address: "Jumeirah", orders: 4, spent: 426, status: "New" },
  ]);
  const [adminOrders, setAdminOrders] = useState<Order[]>([
    { orderId: 1048, customerName: "Maya Khan", restaurantName: "Basil & Ember", itemCount: 3, total: 142, status: "Preparing", createdAt: "Today, 12:42 PM" },
    { orderId: 1047, customerName: "Omar Ali", restaurantName: "Saffron Street", itemCount: 2, total: 89, status: "Ready", createdAt: "Today, 12:31 PM" },
    { orderId: 1046, customerName: "Sara Noor", restaurantName: "Sora Kitchen", itemCount: 4, total: 216, status: "On the way", createdAt: "Today, 12:18 PM" },
    { orderId: 1045, customerName: "Leo Martin", restaurantName: "Basil & Ember", itemCount: 1, total: 58, status: "Delivered", createdAt: "Today, 11:54 AM" },
  ]);
  useEffect(() => { authenticationService.listCustomers().then(data => { if (Array.isArray(data) && data.length) setCustomers(data); }).catch(() => undefined); }, []);
  useEffect(() => { orderService.list().then(data => { if (Array.isArray(data) && data.length) setAdminOrders(data); }).catch(() => undefined); }, []);
  const visibleCustomers = customers.filter(customer => `${customer.name} ${customer.email} ${customer.phone}`.toLowerCase().includes(customerQuery.toLowerCase()));
  const visibleOrders = adminOrders.filter(order => `${order.orderId ?? order.id} ${order.customerName ?? order.customerId} ${order.restaurantName ?? order.restaurantId} ${order.status}`.toLowerCase().includes(orderQuery.toLowerCase()));
  return <div className="dashboard admin-dashboard">
    <aside className="dashboard-sidebar"><button className="brand dashboard-brand" onClick={onBrowse}><span>F</span>foodie</button><p className="portal-label">RESTAURANT ADMIN</p><nav><button className={section==="overview"?"active":""} onClick={() => onSectionChange("overview")}><HomeIcon/>Overview</button><button className={section==="orders"?"active":""} onClick={() => onSectionChange("orders")}><ShoppingBagIcon/>Orders <b>8</b></button><button className={section==="restaurants"?"active":""} onClick={() => onSectionChange("restaurants")}><ChartBarIcon/>Restaurants</button><button className={section==="dishes"?"active":""} onClick={() => onSectionChange("dishes")}><StarIcon/>Dishes</button><button className={section==="customers"?"active":""} onClick={() => onSectionChange("customers")}><UserGroupIcon/>Customers</button></nav><div className="sidebar-profile"><div>{session.name.charAt(0).toUpperCase()}</div><span><strong>{session.name}</strong><small>Administrator</small></span><button onClick={onSignOut} aria-label="Sign out"><ArrowRightStartOnRectangleIcon/></button></div></aside>
    <main className="dashboard-main"><header className="dashboard-header"><div><span className="kicker">{{overview:"WEDNESDAY, 3 SEPTEMBER",orders:"ORDER MANAGEMENT",restaurants:"RESTAURANT DIRECTORY",dishes:"MENU MANAGEMENT",customers:"CUSTOMER DIRECTORY"}[section]}</span><h1>{{overview:`Good afternoon, ${session.name.split(" ")[0]}.`,orders:"All orders",restaurants:"All restaurants",dishes:"All dishes",customers:"All customers"}[section]}</h1></div><div className="dashboard-actions"><button className="notification"><BellIcon/><i/></button><button className="outline-action" onClick={onBrowse}>View restaurant</button></div></header>
      {section === "overview" ? <><section className="metric-grid"><article className="metric-feature"><span>TODAY'S REVENUE</span><strong>AED 8,420</strong><p><b>↑ 12.4%</b> from yesterday</p><div className="mini-bars">{[35,52,44,68,57,76,92].map((h,i)=><i key={i} style={{height:`${h}%`}}/>)}</div></article><article><div className="metric-icon orders"><ShoppingBagIcon/></div><span>Active orders</span><strong>24</strong><p>8 need attention</p></article><article><div className="metric-icon delivery"><TruckIcon/></div><span>Out for delivery</span><strong>11</strong><p>Avg. 28 minutes</p></article><article><div className="metric-icon guests"><UserGroupIcon/></div><span>New customers</span><strong>38</strong><p>↑ 7 this week</p></article></section>
      <section className="dashboard-columns"><article className="panel orders-panel"><div className="panel-heading"><div><span className="kicker">LIVE KITCHEN</span><h2>Recent orders</h2></div><button>View all</button></div><div className="order-table"><div className="table-head"><span>Order</span><span>Customer</span><span>Items</span><span>Total</span><span>Status</span></div>{[["#1048","Maya Khan","3 items","AED 142","Preparing"],["#1047","Omar Ali","2 items","AED 89","Ready"],["#1046","Sara Noor","4 items","AED 216","On the way"],["#1045","Leo Martin","1 item","AED 58","Delivered"]].map((row)=><div className="table-row" key={row[0]}>{row.map((cell,i)=><span key={cell} className={i===4?`status ${cell.toLowerCase().replaceAll(" ","-")}`:""}>{cell}</span>)}</div>)}</div></article><article className="panel popular-panel"><div className="panel-heading"><div><span className="kicker">RESTAURANT INSIGHT</span><h2>Popular locations</h2></div></div>{sampleRestaurants.map((restaurant,index)=><div className="popular-item" key={restaurant.name}><span>{index+1}</span><img src={restaurant.image} alt={`${restaurant.name} interior`}/><div><strong>{restaurant.name}</strong><small>{28-index*6} orders today</small></div><b>★ {restaurant.rating}</b></div>)}</article></section></> :
      section === "customers" ? <section className="customers-view"><div className="customer-summary"><article><span>Total customers</span><strong>{customers.length}</strong><small>Registered accounts</small></article><article><span>Active this month</span><strong>{Math.max(customers.length-1,0)}</strong><small>Returning diners</small></article><article><span>Average orders</span><strong>{customers.length ? Math.round(customers.reduce((sum,c)=>sum+(c.orders??0),0)/customers.length) : 0}</strong><small>Per customer</small></article></div><div className="panel customer-panel"><div className="customer-toolbar"><div><h2>Customer list</h2><p>View customer contact and ordering activity.</p></div><label><MagnifyingGlassIcon/><input value={customerQuery} onChange={event=>setCustomerQuery(event.target.value)} placeholder="Search customers"/></label></div><div className="customer-table"><div className="customer-table-head"><span>Customer</span><span>Contact</span><span>Location</span><span>Orders</span><span>Total spent</span><span>Status</span></div>{visibleCustomers.map(customer=><div className="customer-row" key={customer.customerId}><span className="customer-name"><i>{customer.name.charAt(0)}</i><b>{customer.name}<small>#{String(customer.customerId).padStart(4,"0")}</small></b></span><span><b>{customer.email}</b><small>{customer.phone}</small></span><span>{customer.address}</span><span>{customer.orders ?? "—"}</span><span>{customer.spent ? money(customer.spent) : "—"}</span><span><em className={`customer-status ${customer.status?.toLowerCase() || "active"}`}>{customer.status || "Active"}</em></span></div>)}</div>{!visibleCustomers.length && <div className="customer-empty">No customers match “{customerQuery}”.</div>}</div></section> : section === "orders" ?
      <section className="admin-list-view"><div className="list-summary"><span>{adminOrders.length} orders</span><b>{money(adminOrders.reduce((sum,order)=>sum+(order.total??0),0))} total value</b></div><div className="panel customer-panel"><div className="customer-toolbar"><div><h2>Order list</h2><p>Track every order across all restaurant locations.</p></div><label><MagnifyingGlassIcon/><input value={orderQuery} onChange={event=>setOrderQuery(event.target.value)} placeholder="Search orders"/></label></div><div className="admin-order-table"><div className="admin-order-head"><span>Order</span><span>Customer</span><span>Restaurant</span><span>Items</span><span>Total</span><span>Placed</span><span>Status</span></div>{visibleOrders.map(order=><div className="admin-order-row" key={order.orderId??order.id}><b>#{order.orderId??order.id}</b><span>{order.customerName??`Customer ${order.customerId??"—"}`}</span><span>{order.restaurantName??`Restaurant ${order.restaurantId??"—"}`}</span><span>{order.itemCount??"—"}</span><span>{money(order.total??0)}</span><small>{order.createdAt??"—"}</small><em className={`status ${(order.status??"preparing").toLowerCase().replaceAll(" ","-")}`}>{order.status??"Preparing"}</em></div>)}</div></div></section> :
      <AdminCatalog section={section === "restaurants" ? "restaurants" : "dishes"} onDishes={() => onSectionChange("dishes")}/>}
    </main>
  </div>;
}

function UserDashboard({ session, onBrowse, onSignOut, onCart, section, onSection, onRestaurant, cartContent }: { cartContent?: ReactNode; session: Session; onBrowse: () => void; onSignOut: () => void; onCart: () => void; section: string; onSection: (section: string) => void; onRestaurant: (restaurant: Restaurant) => void }) {
  return <div className="user-dashboard"><header className="user-dash-nav"><button className="brand" onClick={onBrowse}><span>F</span>foodie</button><nav><button className={section === "overview" ? "active" : ""} onClick={() => onSection("overview")}>Overview</button><button className={section === "browse" ? "active" : ""} onClick={onBrowse}>Browse food</button><button className={section === "cart" ? "active" : ""} aria-current={section === "cart" ? "page" : undefined} onClick={onCart}>Cart & checkout</button><button className={section === "favourites" ? "active" : ""} onClick={() => onSection("favourites")}>Favourites</button></nav><div><button className="notification"><BellIcon/></button><button className="user-avatar">{session.name.charAt(0).toUpperCase()}</button><button className="signout" onClick={onSignOut}><ArrowRightStartOnRectangleIcon/> Sign out</button></div></header>
    <main className="user-dash-main">{section === "cart" ? cartContent : section !== "overview" ? <CustomerDiscovery key={session.id} customerId={session.id} favouritesOnly={section === "favourites"} onRestaurant={onRestaurant}/> : <><section className="welcome-strip"><div><span className="kicker">YOUR FOODIE SPACE</span><h1>Welcome back, {session.name.split(" ")[0]}.</h1><p>Your favourites, recent orders and delicious discoveries—all in one place.</p><button onClick={onBrowse}>Find something delicious</button></div><div className="welcome-art"><img src="/images/restaurants/restaurant-hero.jpg" alt="An elegant restaurant dining room"/><span>Tonight's pick<br/><b>Basil & Ember</b></span></div></section>
      <section className="user-stats"><article><ClockIcon/><div><span>Average delivery</span><strong>27 min</strong></div></article><article><ShoppingBagIcon/><div><span>Total orders</span><strong>12</strong></div></article><article><HeartIcon/><div><span>Saved favourites</span><strong>6</strong></div></article></section>
      <section className="user-grid"><article className="panel current-order"><div className="panel-heading"><div><span className="kicker">CURRENT ORDER</span><h2>On its way to you</h2></div><span className="status on-the-way">On the way</span></div><div className="order-progress"><div className="progress-line"><i className="done"/><i className="done"/><i className="active"/><i/></div><div><span>Confirmed</span><span>Preparing</span><span>On the way</span><span>Delivered</span></div></div><div className="current-order-detail"><img src={sampleRestaurants[0].image} alt="Basil & Ember restaurant interior"/><div><strong>Basil & Ember</strong><span>2 × Truffle Burrata Pizza</span><small>Order #1046 · Arriving in 12–18 min</small></div><b>AED 121</b></div></article>
        <article className="panel saved-card"><div className="panel-heading"><div><span className="kicker">SAVED</span><h2>Your favourites</h2></div><button onClick={() => onSection("favourites")}>See all</button></div><div className="saved-restaurants">{sampleRestaurants.slice(0,2).map(r=><button key={r.name} onClick={onBrowse}><img src={r.image} alt=""/><span><strong>{r.name}</strong><small>★ {r.rating} · {r.deliveryTime}</small></span><HeartIcon/></button>)}</div></article></section>
    </>}</main>
  </div>;
}

export default function App() {
  const [path, setPath] = useState(window.location.pathname);
  const [session, setSession] = useState<Session | null>(() => authenticationService.loadSession());
  const [restaurants, setRestaurants] = useState<Restaurant[]>(sampleRestaurants);
  const [selected, setSelected] = useState<Restaurant | null>(null);
  const [dishes, setDishes] = useState<Dish[]>(sampleDishes);
  const customerCart = useCustomerCart(session?.role === "user" ? session.id : undefined);
  const [menuLoading, setMenuLoading] = useState(false);
  const [menuError, setMenuError] = useState("");
  const [query, setQuery] = useState("");
  const [authOpen, setAuthOpen] = useState(() => ["/login", "/register"].includes(window.location.pathname));
  const [authMode, setAuthMode] = useState<"login" | "register">(() => window.location.pathname === "/register" ? "register" : "login");
  const [customerId, setCustomerId] = useState(() => Number(localStorage.getItem("foodieCustomerId")) || 1);
  const [notice, setNotice] = useState("");
  const [busy, setBusy] = useState(false);
  const [offline, setOffline] = useState(false);

  const navigate = (nextPath: string) => { window.history.pushState({}, "", nextPath); setPath(nextPath); };
  useEffect(() => { const handleBack = () => setPath(window.location.pathname); window.addEventListener("popstate", handleBack); return () => window.removeEventListener("popstate", handleBack); }, []);
  useEffect(() => { setAuthOpen(path === "/login" || path === "/register"); setAuthMode(path === "/register" ? "register" : "login"); }, [path]);
  useEffect(() => { restaurantService.list().then(data => { if (Array.isArray(data) && data.length) setRestaurants(data); setOffline(false); }).catch(() => setOffline(true)); }, []);
  const chooseRestaurant = async (restaurant: Restaurant, updateUrl = true) => {
    setSelected(restaurant); if (updateUrl) navigate(`/restaurants/${rid(restaurant)}/dishes`); window.scrollTo({ top: 0, behavior: "smooth" });
    setDishes([]); setMenuLoading(true); setMenuError("");
    try { const data = await dishService.listForRestaurant(rid(restaurant)); if (Array.isArray(data)) setDishes(data); } catch { setMenuError("Unable to load dishes. Please select this restaurant again to retry."); } finally { setMenuLoading(false); }
  };
  useEffect(() => { const match = path.match(/^\/restaurants\/(\d+)\/dishes$/); if (!match) { if (!path.startsWith("/restaurants/")) setSelected(null); return; } const restaurant = restaurants.find(item => rid(item) === Number(match[1])); if (restaurant && (!selected || rid(selected) !== rid(restaurant))) void chooseRestaurant(restaurant, false); }, [path, restaurants]);
  const flash = (message: string, delay = 2400) => { setNotice(message); window.setTimeout(() => setNotice(""), delay); };
  const addDish = async (dish: Dish) => {
    if (!session) { navigate("/login"); return; }
    if (session.role !== "user") { flash("Sign in with a customer account to order."); return; }
    const added = await customerCart.run("add", did(dish));
    if (added) flash(`${dish.name} added to your cart`);
  };
  const itemCount = customerCart.cart?.items.reduce((sum, item) => sum + item.quantity, 0) ?? 0;
  const filtered = restaurants.filter(r => `${r.name} ${r.cuisine ?? ""}`.toLowerCase().includes(query.toLowerCase()));
  const submitAuth = async (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault(); setBusy(true); const payload = Object.fromEntries(new FormData(event.currentTarget).entries());
    try { const result = authMode === "login" ? await authenticationService.login({ email: String(payload.email), password: String(payload.password) }) : await authenticationService.register({ name: String(payload.name), email: String(payload.email), phone: String(payload.phone), address: String(payload.address), password: String(payload.password) }); const nextSession = authenticationService.createSession(result, payload, customerId); setCustomerId(nextSession.id); setSession(nextSession); authenticationService.saveSession(nextSession, result.token); setAuthOpen(false); navigate(nextSession.role === "admin" ? "/admin" : "/dashboard"); flash(authMode === "login" ? "Welcome back!" : "Your account is ready."); }
    catch (e) { flash(e instanceof Error ? e.message : "Something went wrong.", 3000); } finally { setBusy(false); }
  };

  const signOut = () => { authenticationService.clearSession(); setSession(null); navigate("/"); flash("You've signed out."); };
  const adminRouteSection = (path.replace("/admin/", "") || "overview") as AdminSection;
  if (session && path.startsWith("/admin") && session.role === "admin") return <AdminDashboard session={session} section={["overview","orders","restaurants","dishes","customers"].includes(adminRouteSection) ? adminRouteSection : "overview"} onSectionChange={section => navigate(section === "overview" ? "/admin" : `/admin/${section}`)} onBrowse={() => { navigate("/"); }} onSignOut={signOut}/>;
  if (session && (["/dashboard", "/dashboard/browse", "/dashboard/favourites"].includes(path) || (path === "/cart" && session.role === "user"))) return <UserDashboard session={session} cartContent={<CustomerCart state={customerCart} onBrowse={() => navigate("/dashboard/browse")}/>} section={path === "/dashboard" ? "overview" : path.split("/").pop()!} onSection={section => navigate(section === "overview" ? "/dashboard" : `/dashboard/${section}`)} onRestaurant={restaurant => { void chooseRestaurant(restaurant); }} onCart={() => navigate("/cart")} onBrowse={() => navigate("/dashboard/browse")} onSignOut={signOut}/>;

  return <div className="app-shell">
    <header className="topbar"><button className="brand" onClick={() => { setSelected(null); navigate("/"); }} aria-label="Foodie home"><span>F</span>foodie</button><div className="location"><MapPinIcon/><div><small>Deliver to</small><strong>Dubai, UAE</strong></div></div><div className="header-actions"><button className="text-button" onClick={() => { if (session) { navigate(session.role === "admin" ? "/admin" : "/dashboard"); } else navigate("/login"); }}>{session ? "Dashboard" : "Sign in"}</button><button className="bag-button" onClick={() => navigate(session ? "/cart" : "/login")}><ShoppingBagIcon/> Bag <b>{itemCount}</b></button></div></header>
    <main>{path === "/cart" ? (session?.role === "user" ? <CustomerCart state={customerCart} onBrowse={() => navigate("/")}/> : <section className="content-section"><h1>Sign in as a customer to use your cart</h1><button onClick={() => navigate("/login")}>Sign in</button></section>) : !selected ? <><section className="hero"><div className="hero-copy"><div className="eyebrow">GOOD FOOD, GOOD MOOD</div><h1>Your next favourite meal is <em>closer than you think.</em></h1><p>Discover neighbourhood kitchens, local favourites and dishes worth staying in for.</p><label className="search"><MagnifyingGlassIcon/><input value={query} onChange={e => setQuery(e.target.value)} placeholder="Search restaurants or cuisines" /></label><div className="hero-meta"><span>★ 4.8 average rating</span><span>•</span><span>30 min average delivery</span></div></div><div className="hero-image"><img src="/images/restaurants/restaurant-hero.jpg" alt="An elegant restaurant dining room ready for guests"/><div className="floating-card"><span>Places you'll love</span><strong>Exceptional restaurants, delivered</strong></div></div></section>
      <section className="content-section"><div className="section-title"><div><span className="kicker">CURATED FOR YOU</span><h2>Popular near you</h2></div><p>{filtered.length} places ready to deliver</p></div>{offline && <div className="offline-note">Showing today’s sample menu while the local API starts up.</div>}<div className="restaurant-grid">{filtered.map((r, index) => <button className="restaurant-card" key={rid(r)} onClick={() => chooseRestaurant(r)}><div className="restaurant-image"><img src={r.image || restaurantImages[index % restaurantImages.length]} alt={`${r.name} restaurant interior`}/><span>{r.deliveryTime || "25–35 min"}</span></div><div className="restaurant-info"><div><h3>{r.name}</h3><p>{r.cuisine || "Local favourites"}</p></div><div className="rating"><StarIcon/> {r.rating || "4.8"}</div></div><div className="address"><MapPinIcon/>{r.address || "Dubai"}</div></button>)}</div></section></>
      : <section className="menu-page"><button className="back-button" onClick={() => { setSelected(null); navigate("/"); }}><ArrowLeftIcon/> All restaurants</button><div className="restaurant-banner"><img src={selected.image || restaurantImages[0]} alt={`${selected.name} restaurant interior`}/><div className="banner-content"><span>OPEN FOR DELIVERY</span><h1>{selected.name}</h1><p>{selected.cuisine || "Chef-made local favourites"} · {selected.address || "Dubai"}</p><div><b>★ {selected.rating || "4.8"}</b><b>{selected.deliveryTime || "25–35 min"}</b><b>Order online</b></div></div></div><div className="menu-heading"><div><span className="kicker">THE MENU</span><h2>What are you craving?</h2></div><p>Prepared to order with the freshest ingredients.</p></div>{menuError && <p role="alert" className="catalog-error">{menuError}</p>}{customerCart.error && <p role="alert" className="catalog-error">{customerCart.error} <button onClick={() => navigate("/cart")}>View cart</button></p>}{menuLoading && <p role="status">Loading dishes…</p>}{!menuLoading && !menuError && !dishes.length && <p>No dishes available at this restaurant yet.</p>}<div className="dish-grid">{dishes.map((dish, index) => <article className="dish-card" key={did(dish)}><img src={dishPicture(index + 2)} alt={`${dish.name} dish`}/><div><span>{dish.category || "Chef's choice"}</span><h3>{dish.name}</h3><p>{dish.description || "Freshly prepared with carefully selected ingredients."}</p><footer><strong>{money(dish.price)}</strong><button disabled={customerCart.busy || menuLoading} onClick={() => addDish(dish)} aria-label={`Add ${dish.name}`}><PlusIcon/></button></footer></div></article>)}</div></section>}</main>
    {authOpen && <div className="overlay modal-overlay" onMouseDown={() => setAuthOpen(false)}><div className="auth-modal" onMouseDown={e => e.stopPropagation()}><button className="icon-button modal-close" onClick={() => setAuthOpen(false)} aria-label="Close"><XMarkIcon/></button><div className="auth-mark">F</div><span className="kicker">WELCOME TO FOODIE</span><h2>{authMode === "login" ? "Your table is ready." : "Let's get you fed."}</h2><p>{authMode === "login" ? "Sign in to order favourites in a few taps." : "Create an account for a smoother checkout."}</p><form onSubmit={submitAuth}>{authMode === "register" && <><label>Name<input name="name" required placeholder="Your name"/></label><label>Phone<input name="phone" required placeholder="+971 50 123 4567"/></label><label>Address<input name="address" required placeholder="Dubai"/></label></>}<label>Email<input name="email" required type="email" placeholder="you@example.com"/></label><label>Password<input name="password" required type="password" minLength={8} placeholder="At least 8 characters"/></label><button className="primary" disabled={busy}>{busy ? "Please wait…" : authMode === "login" ? "Sign in" : "Create account"}</button></form><button className="switch-auth" onClick={() => setAuthMode(authMode === "login" ? "register" : "login")}>{authMode === "login" ? "New here? Create an account" : "Already a member? Sign in"}</button></div></div>}
    {notice && <div className="toast">{notice}</div>}
  </div>;
}
